### ISSUE TITLE
[FEAT] 목표 기간 내 삭제되지 않은 소비 관련 API

### ISSUE THREAD

**Issue by jwsong98** [UMC-5th-Muffler/Money-Planner-BE#45]
## Description

- 목표 기간 내에 삭제되지 않은 소비 목록 존재 여부 확인 API
- 목표 기간 내에 소비 목록을
- 해당 소비들을 삭제하는 API

## Todo

- [ ] 목표 기간 내 소비 기록이 있는지 검사하는 쿼리
- [ ] 목표 기간 내 소비 목록을 전부 삭제하는 쿼리
- [ ] 목표 기간 내 소비 목록을 생성된 목표에 반영하기
