### ISSUE TITLE
[FEAT] 소비 내역 업데이트 기능

### ISSUE THREAD

**Issue by shortboy7** [UMC-5th-Muffler/Money-Planner-BE#5]
## Description
사용자가 소비 내역을 입력하는 기능
- 목표가 있는 날에만 등록 가능
- 0원 이하 등록 불가능
- 카테고리는 반드시 하나 있어야 함

사용자가 소비 내역을 수정 하는 기능
- 0원 이하 금액으로 수정 불가능
- 목표가 없는 날로 일정 수정 불가능
- 없는 카테고리로 변경 불가능

사용자가 소비 내역을 삭제 하는 기능
- INACTIVE로 변경

## Todo

- [ ] 정상 입력 후 저장
- [ ] 목표가 없는 경우
- [ ] 0원 이하의 금액을 등록하려는 경우
- [ ] 카테고리 없이 등록하려는 경우
- [ ] 사용자가 갖고 있지 않은 카테고리에 등록하려는 경우
