### ISSUE TITLE
[FEAT] 소비 평가 기능

### ISSUE THREAD

**Issue by heejjinkim** [UMC-5th-Muffler/Money-Planner-BE#6]
## Description

- 오늘 목표 금액보다 얼마를 소비 or 아꼈는지 알려준다.
- 오늘의 소비를 평가한다.
- 종합적 평가는 필수, ~각 카테고리 별 평가는 선택 사항~
- ~이때 카테고리는 목표 계획을 새운 카테고리에 대해서만  평가한다.~
- 마지막으로 오늘의 소비 메모(일기)를 입력(선택)

## Todo

- [x] 카테고리별 평가 없어짐
- [x] Rate 테이블 제거 -> DailyPlan 테이블의 칼럼으로 추가

### 조회
- [x] 오늘 목표 금액, 오늘 소비 금액, ~평가 카테고리 리스트~ 반환
- [x] 기존 평가 내역이 있는 경우 반환
- [x] Service 테스트
- [x] Controller 테스트
- [x] ~카테고리 리스트 우선순위 기준 정렬~
- [x] 제로데이 여부 추가 반환
### 등록
- [x] 기존 평가 내역이 반환 X 경우, 등록 api
- [x] ~카테고리 평가는 필수 X~
- [x] Service 테스트
- [x] Controller 테스트
### 수정
- [x] 기존 평가 내역이 반환 O 경우, 수정 api
- [x] ~카테고리 평가는 기존 내역이 없는 경우 새로 생성~
- [x] ~(categoryGoalId, RateId)가 동일한 카테고리 평가는 존재하면 안됨~
- [x] Service 테스트
- [x] Controller 테스트
